apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs
  ports:
    - port: 3000        # Cluster service port
      targetPort: 3000 # Container port
      nodePort: 31111  # Exposed on host for Minikube
